export enum RoutesEnum {
  HOME = '/',
  SEO = '/learn',
  GUIDE = '/guide',
  LETTERS = '/letters',
  NUMBERS = '/numbers',
  COLORS = '/colors',
  SHAPES = '/shapes',
  ANIMALS = '/animals',
  FOOD = '/food',
  GAMES = '/games',
  GUESS_GAME = '/games/guess-game',
  MEMORY_MATCH_GAME = '/games/memory-match-game',
  SIMON_GAME = '/games/simon-game',
  SPEED_CHALLENGE = '/games/speed-challenge',
}
